In [1]:
import numpy as np

In [2]:
mylist = (1,2,3)

In [3]:
type(mylist)

tuple

In [4]:
mylist = {1,2,3}

In [5]:
type(mylist)

set

In [6]:
np.array(mylist)

array({1, 2, 3}, dtype=object)

In [7]:
array = np.array(mylist)

In [8]:
print(array)

{1, 2, 3}


In [9]:
type(array)

numpy.ndarray

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
mytuple = (1,2,3)

In [14]:
myset = {1,2,3}

In [15]:
mylist = [1,2,3]

In [17]:
print("mytuple is of type ", type(mytuple))
print("myset is of type ", type(myset))
print("mylist is of type ", type(mylist))

mytuple is of type  <class 'tuple'>
myset is of type  <class 'set'>
mylist is of type  <class 'list'>


In [23]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [24]:
arr2 = np.random.randint(0,100,10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [26]:
arr3 = np.random.randint(0,100,144)
arr3.reshape(12,12)

array([[68, 61, 18, 51, 14, 28, 17, 87, 46, 52, 16, 70],
       [71, 84, 10, 62, 96, 57, 23, 86, 85, 26, 76, 66],
       [54, 17, 65, 57, 89,  2, 80, 50, 66, 88, 79, 93],
       [ 6, 92, 42, 22, 20, 25, 97, 54, 71, 72, 80, 93],
       [64, 63, 80, 38, 45, 35, 25, 95, 75, 72, 11, 76],
       [79, 50, 22, 59, 66,  1, 34, 37, 57, 35, 42, 44],
       [49, 31, 79, 85,  3, 55, 73, 93, 94, 99, 40, 54],
       [88, 94, 86, 17, 68, 17, 18, 60, 83, 82,  7, 67],
       [34, 76, 94, 20, 69, 73, 59, 34, 69, 25, 78, 92],
       [74, 75, 33,  9, 43, 20, 82, 30,  3, 46, 29, 47],
       [27, 81, 71, 25, 94, 57, 21, 29,  6, 54, 47, 47],
       [60,  6, 75, 97, 53, 44, 98, 39, 32, 87, 78, 21]])

In [28]:
arr4 = np.arange(0,100).reshape(10,10)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
row = 4
column = 6
arr4[row,column]

46

In [31]:
arr4[1:4,3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [36]:
arr5 = np.random.randint(0,255,144).reshape(12,12)

In [44]:
arr6 = arr5.copy()

In [46]:
arr6[0:5, 1:6] = arr6[0:5, 1:6] / 255

In [47]:
arr6

array([[ 88,   0,   0,   0,   0,   0, 224,  19,  77, 124, 118,   5],
       [ 70,   0,   0,   0,   0,   0, 199,  23, 218,  78,  85,  61],
       [231,   0,   0,   0,   0,   0, 169, 189, 184, 243, 130,  86],
       [147,   0,   0,   0,   0,   0,  15, 124, 203,  70, 228,  12],
       [141,   0,   0,   0,   0,   0, 148, 198, 253,  14, 184,  19],
       [207, 235,  59, 161,  33,  11, 104, 172,  43, 239, 251, 221],
       [131, 167, 110, 205, 230, 120, 131, 186, 179, 160,  46, 136],
       [  9, 141, 191, 187, 243, 120,  79, 133, 161, 175, 157, 207],
       [ 62,  25, 122, 244, 249, 228,  43,  46, 222,  68, 183, 242],
       [108,  69, 169,  41, 142, 175, 123, 131, 115, 192,  23,  80],
       [170,  84, 216, 232, 217, 232, 240,  10,  78, 110,  97, 250],
       [ 65,   8,  14, 229, 156, 208, 145, 190,  27, 161,  14, 243]])